env:
  global:
      - REPO_DIR=astropy
      - BUILD_COMMIT=v4.1rc2
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - NP_BUILD_DEP="numpy==1.16.5"
      - NP_TEST_DEP="numpy==1.16.5"
      - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy scipy h5py matplotlib beautifulsoup4 wheel"

language: python
# Default Python version is usually 2.7
python: 3.6
dist: trusty
services: docker

jobs:
  include:
    # add osx first into the queue as they have lower parallelism
    #
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.16.5
        - NP_TEST_DEP=numpy==1.16.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_PYTHON_OSX_VER=10.9
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy beautifulsoup4 wheel"

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
        # Matplotlib doesn't work properly for 32-bit
        - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy scipy h5py beautifulsoup4 wheel"

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.16.5
        - NP_TEST_DEP=numpy==1.16.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.16.5
        - NP_TEST_DEP=numpy==1.16.5
        - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy beautifulsoup4 wheel"

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy beautifulsoup4 wheel"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - GEN_DEPS="pyyaml psutil pytest pytest-doctestplus==0.4.0 pytest-astropy beautifulsoup4 wheel"


before_install:
    # tzdata is included to ensure system leap seconds are up to date.
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
          sudo apt-get install tzdata;
      fi
    - BUILD_DEPENDS="$NP_BUILD_DEP Cython jinja2 wheel extension-helpers setuptools_scm"
    - TEST_DEPENDS="$NP_TEST_DEP $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # trigger an upload to the shared ecosystem
    # infrastructure at: https://anaconda.org/scipy-wheels-nightly
    # for cron jobs only (restricted to master branch once
    # per week)
    # The tokens are set from
    # https://travis-ci.org/github/MacPython/numpy-wheels/settings
    # originally generated at
    # anaconda.org/scipy-wheels-nightly/settings/access
    - ANACONDA_ORG="multibuild-wheels-staging";
      TOKEN=${ASTROPY_STAGING_UPLOAD_TOKEN};
    - pip install git+https://github.com/Anaconda-Server/anaconda-client;
    - if [ -n "${TOKEN}" ] ; then
        anaconda -t ${TOKEN} upload -u ${ANACONDA_ORG} ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl;
      fi
